apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi
