# File: templates/mongodb/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongodb.storage.className }}
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
