apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: {{ .Values.service.backend.port }}
    targetPort: {{ .Values.backend.port }}
