# values.yaml
frontend:
  image:
    repository: jai3747/my-frontend-app
    tag: latest
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

backend:
  image:
    repository: jai3747/my-backend-app
    tag: latest
  service:
    type: LoadBalancer
    port: 5000
    targetPort: 5000

mongodb:
  image:
    repository: mongo
    tag: latest
  persistence:
    size: 1Gi
