# File: templates/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
