# templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-backend
  labels:
    app: backend
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: backend
    release: {{ .Release.Name }}
