# docker-registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": {{ .Values.docker.username | quote }},
          "password": {{ .Values.docker.token | quote }},
          "auth": {{ printf "%s:%s" .Values.docker.username .Values.docker.token | b64enc | quote }}
        }
      }
    }
