# templates/mongodb-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "myapp.fullname" . }}-mongodb
  labels:
    app: mongodb
    release: {{ .Release.Name }}
spec:
  serviceName: {{ include "myapp.fullname" . }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mongodb
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: mongodb
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        command: ["mongod", "--bind_ip_all", "--auth"]
        ports:
        - containerPort: 27017
        resources:
          {{- toYaml .Values.mongodb.resources | nindent 12 }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.auth.existingSecret }}
              key: MONGO_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.auth.existingSecret }}
              key: MONGO_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.mongodb.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.mongodb.persistence.size }}
