# # # # # # templates/mongodb-pvc.yaml
# # # # # apiVersion: v1
# # # # # kind: PersistentVolumeClaim
# # # # # metadata:
# # # # #   name: mongodb-data-claim
# # # # #   labels:
# # # # #     app.kubernetes.io/name: mern-app
# # # # #     app.kubernetes.io/instance: mern-app
# # # # #     app.kubernetes.io/managed-by: Helm
# # # # #     helm.sh/chart: mern-app
# # # # #   annotations:
# # # # #     meta.helm.sh/release-name: mern-app
# # # # #     meta.helm.sh/release-namespace: default
# # # # # spec:
# # # # #   accessModes: [ "ReadWriteOnce" ]
# # # # #   resources:
# # # # #     requests:
# # # # #       storage: 1Gi
# # # # apiVersion: v1
# # # # kind: PersistentVolumeClaim
# # # # metadata:
# # # #   name: {{ .Release.Name }}-mongodb-pvc
# # # #   labels:
# # # #     {{- include "mern-app.labels" . | nindent 4 }}
# # # # spec:
# # # #   accessModes:
# # # #     - ReadWriteOnce
# # # #   resources:
# # # #     requests:
# # # #       storage: {{ .Values.mongodb.persistence.size }}
# # # # templates/mongodb-pvc.yaml
# # # apiVersion: v1
# # # kind: PersistentVolumeClaim
# # # metadata:
# # #   name: {{ .Release.Name }}-mongodb-pvc
# # #   labels:
# # #     {{- include "mern-app.labels" . | nindent 4 }}
# # # spec:
# # #   accessModes:
# # #     - ReadWriteOnce
# # #   resources:
# # #     requests:
# # #       storage: {{ .Values.mongodb.persistence.size }}
# # apiVersion: v1
# # kind: PersistentVolumeClaim
# # metadata:
# #   name: {{ include "mern-app.fullname" . }}-mongodb-pvc
# #   labels:
# #     {{- include "mern-app.labels" . | nindent 4 }}
# # spec:
# #   accessModes:
# #     - ReadWriteOnce
# #   resources:
# #     requests:
# #       storage: {{ .Values.mongodb.persistence.size }}
# # templates/pvc.yaml
# {{- if .Values.mongodb.persistence.enabled }}
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Release.Name }}-mongodb-data
#   labels:
#     {{- include "mern-app.labels" . | nindent 4 }}
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: {{ .Values.mongodb.persistence.size }}
# {{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mern-app.fullname" . }}-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
