# # templates/secrets.yaml
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongodb-secret
#   labels:
#     {{- include "mern-app.labels" . | nindent 4 }}
#   annotations:
#     "helm.sh/hook": pre-install
# type: Opaque
# stringData:
#   MONGO_URI: mongodb+srv://jayachandran:jc%403747%40jai@cluster0.w45he.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  labels:
    {{- include "mern-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
stringData:
  MONGO_URI: {{ .Values.mongodb.uri }}
