# # # # # templates/secrets.yaml
# # # # apiVersion: v1
# # # # kind: Secret
# # # # metadata:
# # # #   name: mongodb-secret
# # # #   labels:
# # # #     {{- include "mern-app.labels" . | nindent 4 }}
# # # #   annotations:
# # # #     "helm.sh/hook": pre-install
# # # # type: Opaque
# # # # stringData:
# # # #   MONGO_URI: mongodb+srv://jayachandran:jc%403747%40jai@cluster0.w45he.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
# # # apiVersion: v1
# # # kind: Secret
# # # metadata:
# # #   name: {{ .Release.Name }}-mongodb-secret
# # #   labels:
# # #     {{- include "mern-app.labels" . | nindent 4 }}
# # #   annotations:
# # #     "helm.sh/hook": pre-install
# # # type: Opaque
# # # stringData:
# # #   MONGO_URI: {{ .Values.mongodb.uri }}
# # # templates/secrets.yaml
# # apiVersion: v1
# # kind: Secret
# # metadata:
# #   name: {{ .Release.Name }}-mongodb-secret
# #   labels:
# #     {{- include "mern-app.labels" . | nindent 4 }}
# # type: Opaque
# # stringData:
# #   MONGO_URI: {{ .Values.mongodb.uri }}

# # templates/secrets.yaml
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ include "mern-app.fullname" . }}-mongodb-secret
#   labels:
#     {{- include "mern-app.labels" . | nindent 4 }}
# type: Opaque
# stringData:
#   MONGO_URI: {{ .Values.mongodb.uri }}
# templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "mern-app.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    {{- include "mern-app.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: 5000
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-backend
