# File: values.yaml
global:
  environment: production

mongodb:
  image:
    repository: mongo
    tag: "6.0.12"
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  storage:
    size: "10Gi"
    className: "standard-rwo"
  credentials:
    secretName: "mongodb-secret"
  replicas: 1

backend:
  name: backend-deployment
  image:
    repository: "${DOCKER_USERNAME}/my-backend-app"
    tag: "${GITHUB_SHA}"
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  port: 5000
  probes:
    readiness:
      path: /api/health
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    liveness:
      path: /api/health
      initialDelaySeconds: 60
      periodSeconds: 20
      timeoutSeconds: 5

frontend:
  name: frontend-deployment
  image:
    repository: "${DOCKER_USERNAME}/my-frontend-app"
    tag: "${GITHUB_SHA}"
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  port: 8080
  probes:
    readiness:
      path: /
      initialDelaySeconds: 30
      periodSeconds: 10
    liveness:
      path: /
      initialDelaySeconds: 60
      periodSeconds: 20

service:
  backend:
    type: LoadBalancer
    port: 5000
  frontend:
    type: LoadBalancer
    port: 80
