version: '3.8'

services:
  frontend:
    build: /Users/jayachandran/Downloads/newofile/frontend-1
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: /Users/jayachandran/Downloads/newofile/backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://jayachandran:jc%403747%40jai@cluster0.w45he.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: